@startuml

node "Spring Application" {
  [Dashboard Controller]
  [Dashboard Service]
  [API Service]
  [User Repository]
  [Activity Repository]
  [Club Repository]
}

cloud {
  [External API]
}

database "PostgreSQL" {
  [DB]
}

HTTP --> [Dashboard Controller]
[Dashboard Controller] --> [Dashboard Service]
[Dashboard Service] --> [API Service]
[Dashboard Service] --> [User Repository]
[Dashboard Service] --> [Activity Repository]
[Dashboard Service] --> [Club Repository]
[API Service] --> [External API]
[User Repository] --> [DB]
[Activity Repository] --> [DB]
[Club Repository] --> [DB]

@enduml